import assert from 'node:assert/strict';
import { randomBytes, scryptSync } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { chromium } from 'playwright';
import { createPool } from './db.js';
import { buildApp } from './app.js';
import { migrateHistory, persistHistory, comparePlaces } from './history.js';
import {migrateContacting,templateSchema,renderTemplate} from './contacting.js';

// Dedicated schema isolates this check from real leads, even on an existing database.
const pool = createPool();
const client = await pool.connect();
const schema = `check_${randomBytes(6).toString('hex')}`;
let app, browser;
try {
  await client.query(`CREATE SCHEMA ${schema}`);
  await client.query(`SET search_path TO ${schema}`);
  await client.query(await readFile(new URL('./schema.sql', import.meta.url), 'utf8'));
  await migrateHistory(client);
  await migrateContacting(client);
  const db = { query: (...args) => client.query(...args), connect: async () => ({ query: (...args) => client.query(...args), release() {} }) };
  const password = randomBytes(16).toString('hex');
  const salt = randomBytes(16).toString('hex');
  const config = { ADMIN_EMAIL: 'test@example.com', ADMIN_PASSWORD_HASH: `${salt}:${scryptSync(password, salt, 64).toString('hex')}`, SESSION_SECRET: randomBytes(32).toString('hex'), INGEST_API_KEY: randomBytes(32).toString('hex'), APP_ORIGIN: 'http://127.0.0.1:3199' };
  app = await buildApp(db, config);
  let response = await app.inject({ method: 'GET', url: '/api/leads' });
  assert.equal(response.statusCode, 401);
  response = await app.inject({ method: 'POST', url: '/api/auth/login', headers: { origin: config.APP_ORIGIN }, payload: { email: config.ADMIN_EMAIL, password } });
  assert.equal(response.statusCode, 200);
  const auth = { cookie: response.headers['set-cookie'].split(';')[0], origin: config.APP_ORIGIN };
  const row = { place_key: 'integration-cafe', nama: 'Cafe Pemeriksaan', alamat: 'Jl. Uji, Kota Bandung, Jawa Barat', rating: '4.7', telepon: '08123456789', website: '', label_pencarian: 'Cafe di Kota Bandung, Jawa Barat', url_maps: 'https://www.google.com/maps/place/Test', ulasan_terbaru: '2 minggu lalu', diambil_pada: new Date().toISOString() };
  const ingest = payload => app.inject({ method: 'POST', url: '/api/internal/leads/upsert', headers: { 'x-api-key': config.INGEST_API_KEY }, payload });
  response = await ingest(row); assert.equal(response.statusCode, 200); const id = response.json().id;
  response = await app.inject({ method: 'PATCH', url: `/api/leads/${id}/status`, headers: auth, payload: { status: 'won' } }); assert.equal(response.statusCode, 200);
  response = await app.inject({ method: 'POST', url: `/api/leads/${id}/notes`, headers: auth, payload: { content: 'Butuh menu online' } }); assert.equal(response.statusCode, 200);
  response = await ingest({ ...row, nama: 'Cafe Pemeriksaan Updated' }); assert.equal(response.json().id, id);
  response = await app.inject({ url: `/api/leads/${id}`, headers: auth });
  assert.equal(response.json().status, 'won'); assert.equal(response.json().notes.length, 1); assert.equal(response.json().history.length, 1);
  assert.equal(response.json().quality.telepon_normalized, '+628123456789');
  assert.equal(response.json().quality.review_date_precision, 'relative');
  assert.throws(()=>templateSchema.parse({name:'Bad',body:'{{unknown}}'}));
  assert.equal(renderTemplate('Halo {{nama}}',{nama:'A&B'}),'Halo A&B');
  response=await app.inject({method:'POST',url:'/api/message-templates',headers:auth,payload:{name:'Intro',body:'Halo {{nama}} & {{kota}}'}});assert.equal(response.statusCode,200);const templateId=response.json().id;
  response=await app.inject({url:`/api/leads/${id}/contact-preview?template_id=${templateId}`,headers:auth});assert.equal(response.statusCode,200);const preview=response.json();assert.ok(preview.url.includes('%26'));
  response=await app.inject({method:'PUT',url:`/api/message-templates/${templateId}`,headers:auth,payload:{name:'Edited',body:'Changed'}});assert.equal(response.statusCode,200);
  response=await app.inject({method:'POST',url:`/api/leads/${id}/contacted`,headers:auth,payload:{token:preview.token,confirmed:true}});assert.equal(response.statusCode,200);
  response=await app.inject({method:'POST',url:`/api/leads/${id}/contacted`,headers:auth,payload:{token:preview.token,confirmed:true}});assert.equal(response.statusCode,200);
  response=await app.inject({method:'DELETE',url:`/api/message-templates/${templateId}`,headers:auth,payload:{confirm:true}});assert.equal(response.statusCode,200);
  response=await app.inject({url:`/api/leads/${id}/contact-history`,headers:auth});assert.equal(response.json().length,1);assert.equal(response.json()[0].template_id,null);assert.equal(response.json()[0].template_name_snapshot,'Intro');assert.equal(response.json()[0].message_snapshot,preview.message);
  response = await app.inject({ url: '/api/leads?website=no&kota=Kota%20Bandung&rating=4&status=won', headers: auth }); assert.equal(response.json().total, 1);
  response = await app.inject({ url: '/api/leads?website=yes', headers: auth }); assert.equal(response.json().total, 0);
  response = await app.inject({ url: '/api/leads/export?status=won', headers: auth }); assert.equal(response.statusCode, 200); assert.ok(response.body.includes('Cafe Pemeriksaan Updated'));
  response = await app.inject({ url: '/api/stats/overview', headers: auth }); assert.equal(response.json().won, 1);
  response = await ingest({ ...row, ulasan_terbaru: 'setahun lalu' }); assert.equal(response.statusCode, 400);
  response = await app.inject({ method: 'PATCH', url: `/api/leads/${id}/status`, headers: { cookie: auth.cookie, origin: 'https://evil.example' }, payload: { status: 'lost' } }); assert.equal(response.statusCode, 403);
  await app.listen({ host: '127.0.0.1', port: 3199 });
  browser = await chromium.launch();
  const page = await browser.newPage();
  const errors = [];
  page.on('pageerror', error => { errors.push(error.message); console.error('BROWSER:', error.message); });
  await page.goto(config.APP_ORIGIN);
  await page.getByLabel('Email', { exact: true }).fill(config.ADMIN_EMAIL);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Masuk ke dashboard' }).click();
  await page.getByRole('link',{name:'Template pesan',exact:true}).click();
  await page.getByLabel('Nama template',{exact:true}).fill('Browser template');
  await page.getByLabel('Isi pesan',{exact:true}).fill('Halo {{nama}}');
  await page.getByRole('button',{name:'Simpan template',exact:true}).click();
  await page.getByRole('button',{name:'Hapus permanen',exact:true}).waitFor();
  await page.getByRole('link', { name: 'Database Lead', exact: true }).click();
  await page.getByRole('button', { name: 'Cafe Pemeriksaan Updated', exact: true }).click();
  await page.getByRole('dialog').waitFor();
  await page.getByLabel('Pilih template',{exact:true}).selectOption({label:'Browser template'});
  await page.getByRole('button',{name:'Preview pesan',exact:true}).click();
  await page.getByRole('link',{name:'Buka WhatsApp',exact:true}).waitFor();
  await page.getByLabel('Catatan baru').fill('Catatan melalui browser');
  await page.getByRole('button', { name: 'Simpan catatan' }).click();
  await page.getByText('Catatan melalui browser', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('link', { name: 'Peluang Web', exact: true }).click();
  await page.getByRole('heading', { name: 'Peluang Web', exact: true }).waitFor();
  await page.getByRole('link', { name: 'Scraping', exact: true }).click();
  await page.getByRole('button', { name: 'Mulai Scraping' }).waitFor();
  auth.cookie = (await page.context().cookies()).filter(c=>c.name==='session').map(c=>`${c.name}=${c.value}`).join('; ');
  response=await app.inject({method:'POST',url:'/api/scraping/preview',headers:auth,payload:{hours:.25,mode:'new',cities:['Kota Bandung'],keywords:['Cafe']}});assert.equal(response.statusCode,200);assert.equal(response.json().queries.length,1);
  response=await app.inject({method:'POST',url:'/api/scraping/start',headers:auth,payload:{hours:.25,mode:'new'}});assert.equal(response.statusCode,400);
  response = await app.inject({ url: '/api/scraping/status', headers: auth }); assert.equal(response.statusCode, 200);
  await client.query("INSERT INTO scrape_jobs(status) VALUES ('running')");
  const historyId=(await client.query('SELECT max(id) id FROM scrape_jobs')).rows[0].id;
  await persistHistory(client,historyId,{config:{hours:4.5},queries:{q:{query:'Cafe di Bandung',city:'Bandung',keyword:'Cafe',status:'incomplete',started_at:new Date().toISOString(),scroll_count:4,result_count:1,reached_end:false}},places:{test:{queries:['Cafe di Bandung'],result_status:'recent',snapshot:{nama:'Test',rating:'4'}}}});
  response=await app.inject({url:`/api/scraping/jobs/${historyId}/coverage`,headers:auth});assert.equal(response.json()[0].incomplete,1);
  assert.equal(comparePlaces([{place_key:'a',snapshot:{rating:4}}],[{place_key:'a',snapshot:{rating:5}}])[0].status,'changed');
  response = await app.inject({ method:'POST',url:'/api/scraping/start',headers:auth,payload:{} }); assert.equal(response.statusCode,409);
  response = await app.inject({ method:'POST',url:'/api/scraping/stop',headers:auth,payload:{} }); assert.equal(response.json().status,'stopping');
  await client.query("UPDATE scrape_jobs SET last_heartbeat=now()-interval '3 minutes'");
  response = await app.inject({ url:'/api/scraping/status',headers:auth }); assert.equal(response.json().status,'failed');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForTimeout(400);
  const overflowing = await page.evaluate(() => ({ width: innerWidth, scroll: document.documentElement.scrollWidth, elements: [...document.querySelectorAll('body *')].filter(e => e.scrollWidth > e.clientWidth + 5 && !e.closest('.table-scroll')).map(e => ({class:e.className,w:e.clientWidth,s:e.scrollWidth,overflow:getComputedStyle(e).overflow})).slice(0, 25) }));
  assert.ok(overflowing.scroll <= overflowing.width, JSON.stringify(overflowing));
  assert.deepEqual(errors, []);
  console.log('PASS: auth, ingest, dedup, persistence, filters, CSV, stats, validation, CSRF, browser login/detail/note, mobile layout.');
} finally {
  await browser?.close(); await app?.close();
  await client.query('SET search_path TO public');
  await client.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);
  client.release(); await pool.end();
}
