import {useEffect,useState} from 'react';
import {Card,CardHeader,CardTitle,CardDescription,CardContent} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Field,FieldGroup,FieldLabel} from '@/components/ui/field';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Checkbox} from '@/components/ui/checkbox';
import {Alert,AlertTitle,AlertDescription} from '@/components/ui/alert';
async function api(path,method='GET',body){const r=await fetch(`/api${path}`,{method,headers:{'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'Permintaan gagal');return d;}
function ErrorBox({error}){return error?<Alert variant="destructive"><AlertTitle>Operasi gagal</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>:null}
export function Templates(){
 const[items,setItems]=useState([]),[form,setForm]=useState({name:'',body:'',is_active:true}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=()=>api('/message-templates').then(setItems);
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await api(`/message-templates${form.id?'/'+form.id:''}`,form.id?'PUT':'POST',form);setForm({name:'',body:'',is_active:true});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function remove(t){if(!window.confirm(`Hapus template "${t.name}" secara permanen? Histori kontak tetap tersimpan.`))return;setBusy(true);try{await api(`/message-templates/${t.id}`,'DELETE',{confirm:true});if(form.id===t.id)setForm({name:'',body:'',is_active:true});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <main className="page"><h1>Template pesan</h1><ErrorBox error={error}/><Card><CardHeader><CardTitle>{form.id?'Edit template':'Buat template'}</CardTitle><CardDescription>Variabel: {'{{nama}}, {{kategori}}, {{kota}}, {{rating}}, {{website}}'}. Preview tersedia di detail lead.</CardDescription></CardHeader><CardContent><form onSubmit={save}><FieldGroup><Field><FieldLabel htmlFor="template-name">Nama template</FieldLabel><Input id="template-name" required maxLength={100} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field><FieldLabel htmlFor="template-body">Isi pesan</FieldLabel><Textarea id="template-body" required maxLength={2000} rows={7} value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></Field><Field orientation="horizontal"><Checkbox id="template-active" checked={form.is_active} onCheckedChange={v=>setForm({...form,is_active:v===true})}/><FieldLabel htmlFor="template-active">Aktif</FieldLabel></Field><div className="flex gap-2"><Button disabled={busy}>Simpan template</Button>{form.id&&<Button type="button" variant="outline" onClick={()=>setForm({name:'',body:'',is_active:true})}>Batal edit</Button>}</div></FieldGroup></form></CardContent></Card>{items.map(t=><Card key={t.id}><CardHeader><CardTitle>{t.name}</CardTitle><CardDescription>{t.is_active?'Aktif':'Nonaktif'}</CardDescription></CardHeader><CardContent><p className="whitespace-pre-wrap break-words text-sm mb-4">{t.body}</p><div className="flex gap-2"><Button variant="outline" disabled={busy} onClick={()=>setForm(t)}>Edit</Button><Button variant="destructive" disabled={busy} onClick={()=>remove(t)}>Hapus permanen</Button></div></CardContent></Card>)}</main>
}
export function ContactLead({lead,changed}){
 const[templates,setTemplates]=useState([]),[selected,setSelected]=useState(''),[preview,setPreview]=useState(null),[history,setHistory]=useState([]),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false),[blocked,setBlocked]=useState(false);
 const disabled=blocked||lead.opted_out_at||lead.status==='do_not_contact';
 const load=()=>api(`/leads/${lead.id}/contact-history`).then(setHistory);
 useEffect(()=>{Promise.all([api('/message-templates').then(setTemplates),load()]).catch(e=>setError(e.message))},[lead.id]);
 async function action(type){setBusy(true);setError('');try{if(type==='preview'){setPreview(await api(`/leads/${lead.id}/contact-preview?template_id=${selected}`));setConfirmed(false);}else if(type==='contacted'){await api(`/leads/${lead.id}/contacted`,'POST',{token:preview.token,note,confirmed:true});setPreview(null);setNote('');await load();changed();}else{await api(`/leads/${lead.id}/opt-out`,'POST',{});setBlocked(true);setPreview(null);changed();}}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <Card><CardHeader><CardTitle>Hubungi melalui WhatsApp</CardTitle><CardDescription>Pesan dikirim manual. Membuka WhatsApp tidak mencatat pengiriman.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4"><ErrorBox error={error}/>{disabled?<p>Lead ditandai jangan dihubungi.</p>:<FieldGroup><Field><FieldLabel htmlFor="contact-template">Pilih template</FieldLabel><NativeSelect id="contact-template" value={selected} onChange={e=>{setSelected(e.target.value);setPreview(null);setConfirmed(false)}}><NativeSelectOption value="">Pilih template</NativeSelectOption>{templates.filter(t=>t.is_active).map(t=><NativeSelectOption key={t.id} value={t.id}>{t.name}</NativeSelectOption>)}</NativeSelect></Field><Button variant="outline" disabled={busy||!selected} onClick={()=>action('preview')}>Preview pesan</Button>{preview&&<><p className="text-sm">Nomor: +{preview.phone}</p><p className="whitespace-pre-wrap break-words text-sm">{preview.message}</p><Button asChild><a href={preview.url} target="_blank" rel="noreferrer">Buka WhatsApp</a></Button><Field><FieldLabel htmlFor="contact-note">Catatan kontak</FieldLabel><Textarea id="contact-note" value={note} maxLength={2000} onChange={e=>setNote(e.target.value)}/></Field><Field orientation="horizontal"><Checkbox id="contact-confirm" checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/><FieldLabel htmlFor="contact-confirm">Saya sudah mengirim pesan ini secara manual.</FieldLabel></Field><Button disabled={busy||!confirmed} onClick={()=>action('contacted')}>Tandai sudah dihubungi</Button></>}<Button variant="destructive" disabled={busy} onClick={()=>{if(window.confirm('Tandai lead ini jangan dihubungi lagi?'))action('opt-out')}}>Jangan hubungi lagi</Button></FieldGroup>}<h3>Riwayat kontak</h3>{history.length?history.map(h=><div key={h.id} className="border rounded-md p-3 text-sm"><p>{h.template_name_snapshot} · {new Date(h.contacted_at).toLocaleString('id-ID')}</p><p>+{h.phone_snapshot}</p><p className="whitespace-pre-wrap break-words my-2">{h.message_snapshot}</p><p>{h.note}</p></div>):<p className="text-sm text-muted-foreground">Belum ada kontak yang dikonfirmasi.</p>}</CardContent></Card>
}
