import { useEffect,useState } from 'react';
import { useLocation,NavLink } from 'react-router-dom';
import { Card,CardHeader,CardTitle,CardDescription,CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { NativeSelect,NativeSelectOption } from '@/components/ui/native-select';
import { Field,FieldGroup,FieldLabel } from '@/components/ui/field';
import { Table,TableHeader,TableHead,TableBody,TableRow,TableCell } from '@/components/ui/table';
import { Alert,AlertTitle,AlertDescription } from '@/components/ui/alert';
export default function History(){
 const location=useLocation(),mode=location.pathname.split('/').at(-1);
 const[jobs,setJobs]=useState([]),[selected,setSelected]=useState(''),[base,setBase]=useState(''),[rows,setRows]=useState([]),[error,setError]=useState(''),[page,setPage]=useState(1);
 const endpoint=mode==='compare'?`/api/scraping/compare?base_id=${base}&compare_id=${selected}`:`/api/scraping/jobs/${selected}/${mode==='coverage'?'coverage':'queries'}`;
 useEffect(()=>{fetch(`/api/scraping/jobs?page=${page}`).then(async r=>{if(!r.ok)throw Error('Gagal memuat histori');return r.json()}).then(setJobs).catch(e=>setError(e.message))},[page]);
 useEffect(()=>{setRows([]);setError('');if(!selected||(mode==='compare'&&!base))return;const c=new AbortController();fetch(endpoint,{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d}).then(setRows).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>c.abort()},[endpoint,selected,base,mode]);
 async function download(){try{const r=await fetch(endpoint+(endpoint.includes('?')?'&':'?')+'format=csv');if(!r.ok)throw Error('Ekspor gagal');const u=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=u;a.download='ProjectAdmin-history.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}catch(e){setError(e.message)}}
 const fields=mode==='compare'?['nama','status','changed_fields']:mode==='coverage'?['city','queries','completed','incomplete','failed','visible_results']:['query','status','result_count','scroll_count','reached_end','error_code'];
 return <main className="page"><h1>{mode==='compare'?'Perbandingan sesi':mode==='coverage'?'Coverage':'Histori scraping'}</h1><div className="flex gap-2 flex-wrap">{['history','coverage','compare'].map(m=><Button asChild variant="outline" key={m}><NavLink to={`/scraping/${m}`}>{m}</NavLink></Button>)}</div><Alert><AlertTitle>Cakupan observasi</AlertTitle><AlertDescription>Hanya hasil Maps yang terlihat. Hasil wilayah menjumlahkan query sehingga dapat beririsan. Tidak muncul pada sesi lain bukan berarti bisnis tutup. Snapshot hanya ada setelah tempat diproses di sesi tersebut.</AlertDescription></Alert>{error&&<Alert variant="destructive"><AlertTitle>Gagal</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}<Card><CardHeader><CardTitle>Pilih sesi</CardTitle><CardDescription>Sesi lama tanpa detail tidak dibuatkan histori perkiraan.</CardDescription></CardHeader><CardContent><FieldGroup>{(mode==='compare'?[[base,setBase,'Sesi awal'],[selected,setSelected,'Sesi pembanding']]:[[selected,setSelected,'Sesi']]).map(([v,set,label])=><Field key={label}><FieldLabel>{label}</FieldLabel><NativeSelect aria-label={label} value={v} onChange={e=>set(e.target.value)}><NativeSelectOption value="">Pilih sesi</NativeSelectOption>{jobs.map(j=><NativeSelectOption value={j.id} key={j.id}>#{j.id} · {j.status} · {new Date(j.started_at).toLocaleString('id-ID')} {j.detailed?'':'(tanpa detail)'}</NativeSelectOption>)}</NativeSelect></Field>)}</FieldGroup><div className="flex gap-2 mt-4"><Button variant="outline" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Sesi sebelumnya</Button><Button variant="outline" disabled={jobs.length<25} onClick={()=>setPage(p=>p+1)}>Sesi berikutnya</Button><Button disabled={!rows.length} onClick={download}>Ekspor CSV</Button></div></CardContent></Card><Card><CardHeader><CardTitle>{rows.length} baris</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow>{fields.map(f=><TableHead key={f}>{f}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((r,i)=><TableRow key={i}>{fields.map(f=><TableCell key={f}>{Array.isArray(r[f])?r[f].join(', '):String(r[f]??'—')}</TableCell>)}</TableRow>)}</TableBody></Table>{!rows.length&&<p className="text-sm text-muted-foreground py-6">Pilih sesi dengan detail histori untuk melihat hasil.</p>}</CardContent></Card></main>
}
